version: '3.3'
services:
  web:
    image: tautiz/web4study
    volumes:
      - ./baigiamasis:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      APACHE_SERVER_NAME: e-shop.local
      APPLICATION_ENV: development

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eshop
      MYSQL_USER: pauuser
      MYSQL_PASSWORD: paupass

volumes:
  db:
    external: false